### ISSUE TITLE
[BUG] Neon OS Release 24.07.24 - wallpaper not rotating

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/neon_debos#164] opened 2024-07-24 21:04 UTC
### Description

Even though gui/settings/display/wallpaper rotation  is set to 'ON' ; there is no rotation
secondly) turning that setting to OFF , backing out, then going in - setting is ON - won't hold selected OFF

### Relevant Code

gui.log from support/troubleshooting package sent to 'support' jul 24_8:57 EDT
[gui_log.txt](https://github.com/user-attachments/files/16367490/gui_log.txt)

### Other Notes

this is in my neon.yaml
```
PHAL:
  ovos-PHAL-plugin-wallpaper-manager:
    module: ovos-PHAL-plugin-wallpaper-manager
    wait_for_gui: false
    lang: en-us
    selected_provider: skill-ovos-homescreen.openvoiceos
```

**Comment by NeonDaniel** [comment] 2024-07-25 00:26
Looks like that's been fixed but not yet made it into a stable release (https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager/compare/0.0.1...0.0.2a7). 

@jarbasal @mikejgray I think that package is ready for a stable release; thoughts?

**Comment by mikejgray** [comment] 2024-07-25 00:27
Don't see why not. No open issues, and it's been in regular use since last year. Sounds stable enough to me!

**Comment by NeonDaniel** [comment] 2024-07-25 00:36
0.0.2, 0.1, or 1.0? It contains breaking changes, but I don't believe behavior is changed (other than bugs being fixed).

I think `0.1.0` is most consistent with other packages, but I have no strong preference.

**Comment by mikejgray** [comment] 2024-07-25 00:42
No strong preference either, probably best to stay consistent with 0.1.0

**Comment by NeonDaniel** [comment] 2024-07-25 01:05
Marking as `invalid` because this regression is from the later beta releases and not the previous stable release.



> No strong preference either, probably best to stay consistent with 0.1.0

https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager/pull/15

**Closed by NeonDaniel** 2024-07-25 01:05 UTC
Labels: bug, invalid
