### ISSUE TITLE
[BUG] System updates appear to blow away `/etc/sysctl.d`

### ISSUE THREAD

**Issue by strugee** [NeonGeckoCom/neon_debos#46] opened 2023-08-21 17:57 UTC
### Description

I had previously created a file in `/etc/sysctl.d` with `echo net.ipv6.conf.all.disable_ipv6=1 | sudo tee /etc/sysctl.d/10-disable-ipv6.conf` to work around #21. This file now appears to be gone - I can't actually confirm it was the system update, but that seems to be the only likely culprit since I rebooted and that didn't cause the file to be removed.

**Comment by NeonDaniel** [comment] 2023-08-28 18:35
I can confirm this data would not be restored after an update (but is saved in `/opt/neon/old_overlay`). Since anything in this directory would be manually added by a user, I'd consider it "advanced usage" so migrating it between updates could be achieved by adding a [`post_update` script](https://neongeckocom.github.io/neon-docs/neon_os/neon_os_updates/#advanced-usage).


I would be open to moving this config over automatically; the main concern is if this might cause breakage if/when system packages or services change and what kinds of errors that might cause

**Comment by strugee** [comment] 2023-08-30 03:31
> I would be open to moving this config over automatically; the main concern is if this might cause breakage if/when system packages or services change and what kinds of errors that might cause

What exactly are you thinking of? I did wonder if this would cause problems if Neon ever needed to install a package that put stuff in `/etc/sysctl.d` - not sure if that's similar to what you had in mind. If we migrate this config we may want to only migrate a specific file (say `/etc/sysctl.d/99-neon-local.conf` or something like that) and install a `README.neon` file in that directory explaining the nuances.

**Comment by NeonDaniel** [comment] 2023-08-30 17:37
> What exactly are you thinking of?

I'm mostly thinking about a case where a user has defined some config that is currently undefined, but Neon might define a conflicting config in the future.

> If we migrate this config we may want to only migrate a specific file (say /etc/sysctl.d/99-neon-local.conf or something like that) and install a README.neon file in that directory explaining the nuances.

This could be a solution since we could be relatively sure that there wouldn't be a filename conflict and user-specified config. One consideration would be what priority the user config should be or if there's any case where an update should override user config (my initial thought is probably no)

**Comment by strugee** [comment] 2023-08-30 19:58
Makes sense. Also FWIW, I have no use case for this functionality anymore: https://github.com/NeonGeckoCom/neon_debos/issues/21#issuecomment-1698457431

**Closed** 2024-01-09 22:25 UTC
Labels: enhancement, wontfix
